/** @type {import('tailwindcss').Config} */
const withMT = require("@material-tailwind/react/utils/withMT");

module.exports = withMT({
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    fontFamily: {
      sans: [
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      satoshi: ["Satoshi", "sans-serif"],
      heading: ["heading", "sans-serif"],
    },
    screens: {
      xs: "480px",
      sm: "640px",
      md: "768px",
      lg: "976px",
      xl: "1280px",
      "2xl": "1440px",
    },
    colors: {
      primary: "#F7F5FF",
      secondary: "#FFF5E5   ",
      brown: "#ff9966",
      pink: "#EDA6E6",
      yellow: "#FFF480",
      blue: "#A8EBEB",
      red: "#FC9298",
      green: "#66CCA0",
      black: "#1B1C1D",
      white: "#ffffff",

      software: "#007ACC",
      software_s: "#FF9900",
      finance: "#008080",
      finance_s: "#FFD700",
      health: "#00B050",
      health_s: "#ffffff",
      education: "#1F7AC8",
      education_s: "#FF6F00",
      food: "#FF9933",
      food_s: "#996633",
      fashion: "#E6007E",
      fashion_s: "#000000",
      realest: "#FF4500",
      realest_s: "#006400",
      consult: "#666666",
      consult_s: "#FFB300",

      f1e9fa: "#f1e9fa",
      e9d8f1: "#e9d8f1",
      e1c7e9: "#e1c7e9",
    },
    extend: {
      boxShadow: {
        md_50: "0 0 15px rgba(0, 0, 0, 0.5)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
});
